spring:
  'application.name': ProjetoIntegrador
  'profiles.active': dev

  config:
    import: "optional:file:.env[.properties]"

  mvc:
    problemdetails:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    connect-retries: 3